/home/pedro/Documents/Shared/GitHub/muJava-AUM/examples/session2/result/Example/traditional_mutants/void_erule21Dummy1()/AORB_1/
/home/pedro/Documents/Shared/GitHub/muJava-AUM/examples/session2/result/Example/traditional_mutants/void_erule21Dummy1()/AORB_2/
/home/pedro/Documents/Shared/GitHub/muJava-AUM/examples/session2/result/Example/traditional_mutants/void_erule21Dummy1()/AORB_3/
/home/pedro/Documents/Shared/GitHub/muJava-AUM/examples/session2/result/Example/traditional_mutants/void_erule21Dummy1()/AORB_4/
/home/pedro/Documents/Shared/GitHub/muJava-AUM/examples/session2/result/Example/traditional_mutants/void_erule21Dummy2()/AORB_5/
/home/pedro/Documents/Shared/GitHub/muJava-AUM/examples/session2/result/Example/traditional_mutants/void_erule21Dummy2()/AORB_6/
/home/pedro/Documents/Shared/GitHub/muJava-AUM/examples/session2/result/Example/traditional_mutants/void_erule21Dummy2()/AORB_7/
/home/pedro/Documents/Shared/GitHub/muJava-AUM/examples/session2/result/Example/traditional_mutants/void_erule21Dummy2()/AORB_8/
/home/pedro/Documents/Shared/GitHub/muJava-AUM/examples/session2/result/Example/traditional_mutants/void_erule21Dummy3()/AORB_9/
/home/pedro/Documents/Shared/GitHub/muJava-AUM/examples/session2/result/Example/traditional_mutants/void_erule21Dummy3()/AORB_10/
/home/pedro/Documents/Shared/GitHub/muJava-AUM/examples/session2/result/Example/traditional_mutants/void_erule21Dummy3()/AORB_11/
/home/pedro/Documents/Shared/GitHub/muJava-AUM/examples/session2/result/Example/traditional_mutants/void_erule21Dummy3()/AORB_12/
/home/pedro/Documents/Shared/GitHub/muJava-AUM/examples/session2/result/Example/traditional_mutants/void_erule21Dummy4()/AORB_13/
/home/pedro/Documents/Shared/GitHub/muJava-AUM/examples/session2/result/Example/traditional_mutants/void_erule21Dummy4()/AORB_14/
/home/pedro/Documents/Shared/GitHub/muJava-AUM/examples/session2/result/Example/traditional_mutants/void_erule21Dummy4()/AORB_15/
/home/pedro/Documents/Shared/GitHub/muJava-AUM/examples/session2/result/Example/traditional_mutants/void_erule21Dummy4()/AORB_16/
/home/pedro/Documents/Shared/GitHub/muJava-AUM/examples/session2/result/Example/traditional_mutants/void_erule21Dummy5()/AORB_17/
/home/pedro/Documents/Shared/GitHub/muJava-AUM/examples/session2/result/Example/traditional_mutants/void_erule21Dummy5()/AORB_18/
/home/pedro/Documents/Shared/GitHub/muJava-AUM/examples/session2/result/Example/traditional_mutants/void_erule21Dummy5()/AORB_19/
/home/pedro/Documents/Shared/GitHub/muJava-AUM/examples/session2/result/Example/traditional_mutants/void_erule21Dummy5()/AORB_20/
/home/pedro/Documents/Shared/GitHub/muJava-AUM/examples/session2/result/Example/traditional_mutants/void_erule21Dummy6()/AORB_21/
/home/pedro/Documents/Shared/GitHub/muJava-AUM/examples/session2/result/Example/traditional_mutants/void_erule21Dummy6()/AORB_22/
/home/pedro/Documents/Shared/GitHub/muJava-AUM/examples/session2/result/Example/traditional_mutants/void_erule21Dummy6()/AORB_23/
/home/pedro/Documents/Shared/GitHub/muJava-AUM/examples/session2/result/Example/traditional_mutants/void_erule21Dummy6()/AORB_24/
